name = "cf-worker-redirects"
main = "src/index.js"
compatibility_date = "2024-04-15"

account_id = "d3b9d419627ff086331fdc4847bd8644"

routes = [
  { pattern = "divulgacao.yanbraga.com/*", zone_name = "yanbraga.com" },
  { pattern = "drive.yanbraga.com/*", zone_name = "yanbraga.com" }
]
